### ISSUE TITLE
i am Github campus expert and mlh local host i want to do a podcast .

### ISSUE THREAD

**Issue by madilraza** [jamstack/JAMstackRadio#15]
Topic is microservices and microfrontend with docder and jamstack

**Comment by bdougie** [comment]
Hey @madilraza. Do you have a link to docder? I am not familiar with it.

**Comment by madilraza** [comment]
https://www.docker.com/why-docker
Developing apps today requires so much more than writing code. Multiple languages, frameworks, architectures, and discontinuous interfaces between tools for each lifecycle stage creates enormous complexity. Docker simplifies and accelerates your workflow, while giving developers the freedom to innovate with their choice of tools, application stacks, and deployment environments for each project.
